CREEP_STRENGTH_MULTIPLIER = 0.18

CREEP_STRENGTH_BARRACKS_POINTS_LOSS = 8

CREEP_STRENGTH_BARRACKS_POINTS = 5
CREEP_STRENGTH_TOWER_VERYEASY_POINTS = 1
CREEP_STRENGTH_TOWER_EASY_POINTS = 1
CREEP_STRENGTH_TOWER_MEDIUM_POINTS = 1
CREEP_STRENGTH_TOWER_HARD_POINTS = 2
CREEP_STRENGTH_TOWER_EXTREME_POINTS = 4
CREEP_STRENGTH_TOWER_ULTIMATE_POINTS = 5

HERO_MOVESPEED_LIMIT = 1150